### PR TITLE
smn gemburst bugfix, blm aoe combo, and sam shoha combo features

### PR DESCRIPTION
**Pull request by lhn1703**
more qol combos

### CODE REVIEW

**Comment by daemitus** [comment]
is shinten>shoha just for parity with aoe?

**Comment by lhn1703** [comment]
yes, single target parity

**Comment by daemitus** [comment]
ive pulled in everything but scholar stuff. its still on my TODO list

**Comment by lhn1703** [comment]
just realized blm doesn't get umbral hearts til lvl 58, could be problematic for fire2 aoe feature when synced to levels 50-58.

**Comment by daemitus** [comment]
```
if (level >= BLM.Levels.Despair && LocalPlayer?.CurrentMp < 2400)
    return BLM.Despair;
```

You're basically looking for something like this, which I've added and should be able soon-ish. 

How should the freeze/flare aoe be reworked?

**Comment by daemitus** [comment]
scholar spender stuff in. open an issue for the blm aoe sync stuff so we can continue it there.

**Pull request closed without merging**
