### PR TITLE
[FEATURE] Expanded Monk form features

### LINKED ISSUE #101: [Optimality] Some suggestions for Ninja,Warrior and Monk
Hi,Mr Daemitus, Thanks for giving us a great plugin. I main play ninja ,warrior and monk.  I had used a few Xivcombo modified edition, I prefer your plugins due to less memory consumption and less FPS drop-off  in game . I have some suggestions for current plugins. No offense.  some suggestions are from another similar plugins.

**Ninja**:  
please add Huraijin into main combo if huton buff is not present (buff timer=0).
image

**Warrior**:

Option 1: In 6.0 endwalker, only Fell Cleave(Inner Chaos) and Decimate(Chaotic Cyclone) cost the Beast Gauge. So warrior is no longer to accumulate gauge over 50. but the overcap logic of plugin is that do not use fell cleave and decimate until 90. but in some points, this logic will make an conflict with main combo even gauge already reached 90. which it would put main combo skill into first priority rather than Fell Cleave/ Decimate. the result is main combo skills (Maim or Storm's Path) make  gauge overcap 10 or 20 besast.  the suggestion is that can you adjust overcap setting from 90 to 50 or 70 in case conflict with main combo. please take a look as picture below

image

Option 2: Please add this feature in to current plugins
image

**Monk**:
Please add Option: 'Twin Snakes' changes into 'True Strike' if you have the 'Disciplined Fist' buff > 5 seconds.

Thank you for be patient with me ^_^

### PR DESCRIPTION
**Pull request by kaedys**
- Added a feature combining Twin Snakes and True Strike.
- Added a feature combining Demolish and Snap Punch
- Reworded 'Dragon Bootshine Feature' to 'Dragon Kick / Bootshine Feature'.  Functionality unchanged.

Partially fixes #101

### CODE REVIEW

**Comment by daemitus** [comment]
added. I think the twin snakes buff is just discplined fist, unless its different synced

**Comment by kaedys** [comment]
Oh derp, you're right, they changed the name on the buff, didn't they?  Good catch.  Also good catch on the levels. >.<

**Comment by kaedys** [comment]
@daemitus looks like you made an oopsie on the Demolish line, it's an AND instead of an OR, so it only triggers if the user is less than Demolish level _and_ their Demolish is on the target >.<

https://github.com/daemitus/XIVComboPlugin/commit/6bd8c57c576f77577c3a09f9f9a55371f8bc8549#diff-a44e803476bae85ab7fe89ae5c70314ce7cf39de80ccdae9caded724c68eaf3eR227

**Comment by daemitus** [comment]
fixed

**Pull request closed without merging**
